name: Testnet harvest vault 0

on:
  schedule:
    - cron: '5 */3 * * *' # at minute 5 past every 3rd hour
  workflow_dispatch:

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke testnet harvest on vault 0
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/97/0xD413Fb9E684bAFEE48e7BBA7A4F3868d4738A3eD -H "Authorization:$APP_SECRET"
