name: Testnet harvest vault 1

on:
  schedule:
    - cron: '10 */3 * * *' # at minute 10 past every 3rd hour
  workflow_dispatch:

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke testnet harvest on vault 1
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/97/0x1fF4570b91B6980C0e1Fc01951e35320d38ff7Eb -H "Authorization:$APP_SECRET"
