name: Cron Test

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke test
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
          JOB_ID: ${{ github.job }}
        run: curl https://automator.ballena.io/cronTest -H "Authorization:$APP_SECRET"
