name: Cron Test

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke test
        env:
          TEST_APP_SECRET: ${{ secrets.TEST_APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl $APP_BASE_URL/cronTest -H "Authorization:$TEST_APP_SECRET"
