name: Testnet harvest vault 0

on:
  schedule:
    - cron: '5 14/8 * * *' # on minute 5 every 8 hours from hour 14
  workflow_dispatch:

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke testnet harvest on vault 0
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/97/0x6AcA1E8FFD398Aea2F23C8742EAD44B3A95F50ba -H "Authorization:$APP_SECRET"
