name: Mainnet harvest BTCST-BNB vault (4)

on:
  schedule:
    - cron: '8 */3 * * *' # at minute 8 past every 3rd hour

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke mainnet harvest on BTCST-BNB vault (4)
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/56/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82/0x2eaF996C82851A0019fbF5295253B02c1Cf397eb/10 -H "Authorization:$APP_SECRET"
