name: Testnet harvest vault 3

on:
  schedule:
    - cron: '20 06,12,18,00 * * *' # on minute 20 every 6 hours from hour 06
  workflow_dispatch:

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke testnet harvest on vault 3
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/97/0xccEeDBa4870cFCFa07f2C14952903721faB4d4Cb -H "Authorization:$APP_SECRET"
