name: Testnet harvest vault 1

on:
  schedule:
    - cron: '10 06,12,18,00 * * *' # on minute 10 every 6 hours from hour 06
  workflow_dispatch:

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke testnet harvest on vault 1
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/97/0xcbd94aac8d55e574150047b187312c982efb905c -H "Authorization:$APP_SECRET"
