name: Mainnet harvest vault 14

on:
  schedule:
    - cron: '28 */3 * * *' # at minute 28 past every 3rd hour

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke mainnet harvest on vault 14
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/56/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82/0xE28Fa263B54E9f5beFB39695Bb728562A3c51237/9 -H "Authorization:$APP_SECRET"
