name: Mainnet harvest WELL-BUSD vault (16)

on:
  schedule:
    - cron: '32 */3 * * *' # at minute 32 past every 3rd hour

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke mainnet harvest on WELL-BUSD vault (16)
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/56/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82/0x80E42210727Eb0Fd214dEdbC66c77cD5D495c0Cf/10 -H "Authorization:$APP_SECRET"
