name: Testnet harvest vault 0

on:
  schedule:
    - cron: '5 06,12,18,00 * * *' # on minute 5 every 6 hours from hour 06
  workflow_dispatch:

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke testnet harvest on vault 0
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/97/0x1Cbd26cBf1e78bd84E365dF88C4fb0b8f0F49A5e -H "Authorization:$APP_SECRET"
