name: Mainnet harvest UST-BUSD vault (15)

on:
  schedule:
    - cron: '30 */3 * * *' # at minute 30 past every 3rd hour

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke mainnet harvest on UST-BUSD vault (15)
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/56/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82/0x65e55E7DFE2a7c3eE39C8EDf8e573554BB9cE87B/10 -H "Authorization:$APP_SECRET"
