name: Mainnet harvest LINK-BNB vault (13)

on:
  schedule:
    - cron: '26 */3 * * *' # at minute 26 past every 3rd hour

jobs:
  test-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke mainnet harvest on LINK-BNB vault (13)
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          APP_BASE_URL: ${{ secrets.BASE_URL }}
        run: curl -if $APP_BASE_URL/harvest/56/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82/0xf416054AC4FA769A17eC50421553a503e236e768/10 -H "Authorization:$APP_SECRET"
